name: Halpme Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # React 빌드 후 Nginx에 배포
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. npm 의존성 캐싱
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 3. Node.js 환경 준비
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 5. React 빌드
      - name: Build
        run: npm run build

      # 6. 빌드 파일 Nginx에 배포
      - name: Deploy build to Nginx directory
        run: |
          sudo rm -rf /var/www/halpme-frontend-temp/* /var/www/halpme-frontend-temp/.[!.]*
          sudo cp -r build/* /var/www/halpme-frontend-temp/
          sudo rm -rf /var/www/halpme-frontend/* /var/www/halpme-frontend/.[!.]*
          sudo mv /var/www/halpme-frontend-temp/* /var/www/halpme-frontend/
          sudo mv /var/www/halpme-frontend-temp/.[!.]* /var/www/halpme-frontend/ 2>/dev/null || true